package com.higgin.weather;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.3
 * 2018-03-25T15:36:38.518+08:00
 * Generated source version: 3.2.3
 *
 */
@WebService(targetNamespace = "http://weather.Higgin.com/", name = "WeatherInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface WeatherInterface {

    @WebMethod
    @RequestWrapper(localName = "queryWeather", targetNamespace = "http://weather.Higgin.com/", className = "com.higgin.weather.QueryWeather")
    @ResponseWrapper(localName = "queryWeatherResponse", targetNamespace = "http://weather.Higgin.com/", className = "com.higgin.weather.QueryWeatherResponse")
    @WebResult(name = "result", targetNamespace = "")
    public java.util.List<com.higgin.weather.WeatherModel> queryWeather(
        @WebParam(name = "cityName", targetNamespace = "")
        java.lang.String cityName
    );
}
